import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { StatusBar } from "expo-status-bar";
import { getFunctions, httpsCallable } from "firebase/functions";
import * as Clipboard from "expo-clipboard";
import { useEffect, useState } from "react";
import { Alert, Pressable, Share, View, useColorScheme } from "react-native";

import { CuteButton } from "../../components/CuteButton";
import { CuteCard } from "../../components/CuteCard";
import { CuteText } from "../../components/CuteText";
import { CuteTextInput } from "../../components/CuteTextInput";
import { Screen } from "../../components/Screen";
import { useAppData } from "../../context/AppDataContext";
import {
  DEFAULT_LOVE_LANGUAGES,
  normalizeLoveLanguages,
} from "../../data/loveLanguages";
import { firebaseApp } from "../../firebase/config";
import {
  coupleService,
  inviteService,
  profileService,
  userService,
} from "../../firebase/services";
import { DBProfile } from "../../firebase/types";
import { usePalette } from "../../hooks/usePalette";
import { PartnerProfile } from "../../types/app";
import { calculateDaysTogether } from "../../utils/dateUtils";
import { useToast } from "../../context/ToastContext";

export default function PairingScreen() {
  const palette = usePalette();
  const scheme = useColorScheme();
  const {
    state: { pairing, auth, profiles },
    dispatch,
  } = useAppData();
  const { showToast } = useToast();

  const [joinCode, setJoinCode] = useState("");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [infoMessage, setInfoMessage] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isJoining, setIsJoining] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);

  const inviteCode = pairing.inviteCode;
  const inviteLink =
    pairing.inviteLink ??
    (inviteCode ? `https://couple.ly/invite/${inviteCode}` : null);

  const joinLabel = isJoining ? "Joining..." : "Join couple";

  const mapDbProfileToPartner = (
    uid: string,
    profile: DBProfile
  ): PartnerProfile => ({
    uid,
    displayName: profile.displayName,
    status: profile.status,
    avatarUrl: profile.avatarUrl ?? undefined,
    about: profile.about,
    accentColor: profile.accentColor,
    loveLanguages: normalizeLoveLanguages(profile.loveLanguages),
  });

  const normalizeFunctionsCode = (code?: string) =>
    code?.startsWith("functions/") ? code.replace("functions/", "") : code;

  const resolveJoinErrorMessage = (error: unknown) => {
    const typed = error as { code?: string; message?: string };
    const rawCode = typeof typed?.code === "string" ? typed.code : undefined;
    const code = normalizeFunctionsCode(rawCode);
    const message = typeof typed?.message === "string" ? typed.message : null;

    switch (code) {
      case "invalid-argument":
        return "That invite code looks invalid. Double-check the 6 characters.";
      case "not-found":
        return "We couldn't find that invite. Ask your partner for a fresh code.";
      case "already-exists":
        return "This invite was already used. Ask your partner to refresh their invite.";
      case "deadline-exceeded":
        return "This invite expired. Ask your partner to generate a new code.";
      case "failed-precondition":
        return (
          message ??
          "You can't join this invite. Make sure you're not already paired and try again."
        );
      case "unauthenticated":
        return "Please sign in again before joining.";
      case "unavailable":
        return "We couldn't connect to join right now. Check your connection and try again.";
      default:
        if (message?.toLowerCase().includes("network")) {
          return "Network issue while joining. Try again in a moment.";
        }
        return (
          message ??
          "We couldn't join with that code. Double-check and try again."
        );
    }
  };

  const handleCreateInvite = async (refresh = false) => {
    if (!auth.user.uid) {
      setErrorMessage("Please sign in again to generate a fresh invite.");
      return;
    }
    if (pairing.inviteCode && !refresh) {
      setErrorMessage(null);
      showToast({
        tone: "info",
        title: "Invite ready",
        message: "Share this code with your partner.",
      });
      return;
    }
    try {
      setIsGenerating(true);
      const ownerName =
        profiles.me?.displayName ?? auth.user.displayName ?? "You";
      const hostAnniversary = auth.user.anniversaryDate ?? null;

      let coupleId = pairing.coupleId ?? auth.user.coupleId;
      let code = refresh ? null : pairing.inviteCode ?? null;
      let shareLink = pairing.inviteLink ?? null;

      if (!coupleId) {
        code = inviteService.generateInviteCode();
        coupleId = await coupleService.createCouple(auth.user.uid, code);
        await userService.updateUser(auth.user.uid, {
          displayName: ownerName,
          avatarUrl: profiles.me?.avatarUrl ?? null,
          coupleId,
        });
      }

      if (profiles.me) {
        await profileService.createProfile(coupleId, auth.user.uid, {
          displayName: profiles.me.displayName,
          status: profiles.me.status,
          avatarUrl: profiles.me.avatarUrl ?? null,
          about: profiles.me.about ?? "",
          accentColor: profiles.me.accentColor,
          emoji: "💕",
          loveLanguages: profiles.me.loveLanguages,
          birthday: auth.user.birthday ?? null,
          anniversary: hostAnniversary,
        });
      }

      if (hostAnniversary) {
        await coupleService.setAnniversary(coupleId, hostAnniversary);
      }

      const ensuredCode = await inviteService.createInvite(
        coupleId,
        ownerName,
        profiles.me?.avatarUrl,
        code ?? undefined
      );

      if (refresh || !code) {
        shareLink = `https://couple.ly/invite/${ensuredCode}`;
        await coupleService.setInviteMetadata(coupleId, ensuredCode);
      }

      const finalLink = shareLink ?? `https://couple.ly/invite/${ensuredCode}`;

      dispatch({
        type: "CREATE_INVITE",
        payload: {
          coupleId,
          inviteCode: ensuredCode,
          inviteLink: finalLink,
          qrCodeData: null,
        },
      });
      setErrorMessage(null);
      setInfoMessage(null);
      setAutoGenerated(true);
    } catch (error) {
      console.error("Failed to create invite", error);
      setErrorMessage(
        error instanceof Error
          ? error.message
          : "We couldn't create your invite. Please try again."
      );
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    const shouldAutoGenerate =
      !pairing.isPaired && !inviteCode && !isGenerating && !autoGenerated;
    if (shouldAutoGenerate) {
      setAutoGenerated(true);
      handleCreateInvite();
    }
  }, [autoGenerated, inviteCode, isGenerating, pairing.isPaired]);

  const handleJoinCouple = async () => {
    const trimmed = joinCode.trim().toUpperCase();
    if (!trimmed) {
      setErrorMessage("Enter the 6-digit invite code your partner shared.");
      setInfoMessage(null);
      return;
    }
    if (trimmed.length !== 6) {
      setErrorMessage("Invite codes are six characters long.");
      setInfoMessage(null);
      return;
    }
    if (!auth.user.uid) {
      setErrorMessage("Please sign in again before joining.");
      setInfoMessage(null);
      return;
    }
    if (pairing.isPaired) {
      setErrorMessage(
        "You're already paired. Reset pairing before joining a new invite."
      );
      setInfoMessage(null);
      return;
    }

    try {
      setIsJoining(true);
      setErrorMessage(null);
      setInfoMessage(null);
      const functions = getFunctions(firebaseApp, "australia-southeast1");
      const redeemInvite = httpsCallable(functions, "redeemInvite");
      const response = await redeemInvite({ code: trimmed });
      const coupleId = (response.data as { coupleId?: string })?.coupleId;

      if (!coupleId) {
        throw new Error(
          "We couldn't verify that invite. Try again in a moment."
        );
      }

      const myProfile = profiles.me;
      if (myProfile) {
        await profileService.createProfile(coupleId, auth.user.uid, {
          displayName: myProfile.displayName,
          status: myProfile.status,
          avatarUrl: myProfile.avatarUrl ?? null,
          about: myProfile.about ?? "",
          accentColor: myProfile.accentColor,
          emoji: "💕",
          loveLanguages: myProfile.loveLanguages,
          birthday: auth.user.birthday ?? null,
          anniversary: auth.user.anniversaryDate ?? null,
        });
      }

      await userService.updateUser(auth.user.uid, {
        displayName: myProfile?.displayName ?? auth.user.displayName ?? "",
        avatarUrl: myProfile?.avatarUrl ?? auth.user.avatarUrl ?? null,
        coupleId,
      });

      const coupleDetails = await coupleService.getCouple(coupleId);
      const hostAnniversary = coupleDetails?.anniversaryDate ?? null;

      if (hostAnniversary) {
        dispatch({
          type: "SET_ANNIVERSARY",
          payload: {
            anniversaryDate: hostAnniversary,
            daysTogether: calculateDaysTogether(hostAnniversary),
          },
        });
      }

      const profileData = await profileService.getCoupleProfiles(coupleId);
      const partnerEntry =
        profileData.partner && profileData.partner.uid !== auth.user.uid
          ? profileData.partner
          : profileData.me && profileData.me.uid !== auth.user.uid
          ? profileData.me
          : undefined;

      if (!partnerEntry) {
        setErrorMessage(
          "You're paired! We’ll pull in your partner’s profile as soon as they finish onboarding."
        );
      }

      const partnerProfile = partnerEntry
        ? mapDbProfileToPartner(partnerEntry.uid, partnerEntry)
        : {
            uid: "pending-partner",
            displayName: "Partner",
            status: "Excited!",
            accentColor: "#A2D2FF",
            about:
              "Your partner will finish setting up soon. Until then, enjoy a preview!",
            avatarUrl: undefined,
            loveLanguages: [...DEFAULT_LOVE_LANGUAGES],
            birthday: undefined,
          };

      dispatch({
        type: "JOIN_COUPLE",
        payload: {
          coupleId,
          partnerProfile,
        },
      });
      setJoinCode("");
      setErrorMessage(null);
      setInfoMessage(null);
      router.replace("/(tabs)");
    } catch (error) {
      console.error("Failed to join couple", error);
      setErrorMessage(resolveJoinErrorMessage(error));
      setInfoMessage(null);
    } finally {
      setIsJoining(false);
    }
  };

  const handleCopyInvite = async () => {
    const code = inviteCode?.trim();
    if (!code) {
      setErrorMessage("Generate an invite first.");
      setInfoMessage(null);
      return;
    }
    try {
      await Clipboard.setStringAsync(code);
      setErrorMessage(null);
      setInfoMessage(null);
      showToast({ tone: "success", message: "Invite code copied!" });
    } catch (err) {
      console.error("Copy invite failed", err);
      try {
        await Share.share({ message: code });
        setErrorMessage(null);
        setInfoMessage(null);
        showToast({ tone: "info", message: "Invite code ready to share." });
      } catch (shareErr) {
        console.error("Share invite failed", shareErr);
        setErrorMessage("Couldn't copy the invite. Please try again.");
        setInfoMessage(null);
      }
    }
  };

  return (
    <Screen
      contentContainerStyle={{
        paddingHorizontal: 20,
        paddingTop: 16,
        gap: 24,
      }}
    >
      <StatusBar style={scheme === "dark" ? "light" : "dark"} />
      <View style={{ gap: 12 }}>
        <View style={{ flexDirection: "row", alignItems: "center", gap: 12 }}>
          <Pressable
            onPress={() => router.back()}
            style={{
              width: 40,
              height: 40,
              borderRadius: 20,
              backgroundColor: palette.card,
              alignItems: "center",
              justifyContent: "center",
              shadowColor: "#000",
              shadowOpacity: 0.08,
              shadowRadius: 6,
              elevation: 2,
            }}
          >
            <MaterialIcons
              name="arrow-back"
              size={20}
              color={palette.textSecondary}
            />
          </Pressable>
          <View style={{ flex: 1 }}>
            <CuteText weight="bold" style={{ fontSize: 26 }}>
              Invite your partner
            </CuteText>
          </View>
        </View>
      </View>

      <View style={{ gap: 16 }}>
        <CuteCard
          background={palette.card}
          padding={20}
          style={{
            gap: 12,
            borderWidth: 1,
            borderColor: palette.primary + "55",
            borderStyle: "dashed",
          }}
        >
          <View
            style={{
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <CuteText weight="bold">Create Couple</CuteText>
            <MaterialIcons name="launch" size={20} color={palette.primary} />
          </View>
          <CuteText tone="muted" style={{ fontSize: 13 }}>
            Generate a private invite code, deep link, and QR to share with your
            person.
          </CuteText>
          {inviteCode ? (
            <View style={{ gap: 14, alignItems: "center" }}>
              <View
                style={{
                  borderWidth: 1,
                  borderColor: palette.primary + "99",
                  borderStyle: "dashed",
                  borderRadius: 20,
                  padding: 18,
                  gap: 10,
                  alignItems: "center",
                  backgroundColor: palette.background,
                }}
              >
                <CuteText tone="muted" style={{ fontSize: 12 }}>
                  Your invite code
                </CuteText>
                <View
                  style={{
                    flexDirection: "row",
                    alignItems: "center",
                    gap: 10,
                  }}
                >
                  <CuteText
                    weight="bold"
                    style={{ fontSize: 34, letterSpacing: 2 }}
                  >
                    {inviteCode}
                  </CuteText>
                  <Pressable
                    onPress={handleCopyInvite}
                    style={{
                      padding: 10,
                      borderRadius: 12,
                      backgroundColor: palette.primary,
                    }}
                    hitSlop={8}
                  >
                    <MaterialIcons name="content-copy" size={18} color="#fff" />
                  </Pressable>
                </View>
                <CuteText tone="muted" style={{ fontSize: 12 }}>
                  Share this code with your partner.
                </CuteText>
              </View>
              <CuteButton
                label="Refresh code"
                tone="ghost"
                onPress={() => handleCreateInvite(true)}
                disabled={isGenerating}
                icon={
                  <MaterialIcons
                    name="refresh"
                    size={18}
                    color={palette.primary}
                  />
                }
                labelColor={palette.primary}
                style={{ minWidth: 200 }}
              />
            </View>
          ) : (
            <View style={{ gap: 10 }}>
              <CuteText tone="muted" style={{ fontSize: 13 }}>
                {isGenerating
                  ? "Generating your private invite..."
                  : "Preparing your invite code. If it takes too long, try again."}
              </CuteText>
              <CuteButton
                label={isGenerating ? "Generating..." : "Try again"}
                onPress={() => handleCreateInvite(true)}
                disabled={isGenerating}
                style={{ alignSelf: "flex-start", minWidth: 160 }}
              />
            </View>
          )}
        </CuteCard>

        {infoMessage ? (
          <CuteCard
            background={palette.primary + "12"}
            padding={14}
            style={{
              flexDirection: "row",
              alignItems: "center",
              gap: 10,
              borderWidth: 1,
              borderColor: palette.primary + "60",
            }}
          >
            <MaterialIcons
              name="check-circle"
              size={18}
              color={palette.primary}
            />
            <CuteText style={{ flex: 1, color: palette.text }}>
              {infoMessage}
            </CuteText>
          </CuteCard>
        ) : null}

        <CuteCard
          background={palette.card}
          padding={20}
          style={{
            gap: 12,
            borderWidth: 1,
            borderColor: palette.border,
            borderStyle: "dashed",
          }}
        >
          <View
            style={{
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <CuteText weight="bold">Join Couple</CuteText>
            <MaterialIcons name="favorite" size={20} color={palette.primary} />
          </View>
          <CuteText tone="muted" style={{ fontSize: 13 }}>
            Already received an invite? Enter the 6-digit code or scan the QR.
          </CuteText>
          <CuteTextInput
            label="Invite code"
            placeholder="123456"
            value={joinCode}
            onChangeText={(value) => {
              setJoinCode(value);
              setErrorMessage(null);
              setInfoMessage(null);
            }}
            keyboardType="number-pad"
            maxLength={6}
          />
          {errorMessage ? (
            <CuteText
              tone="muted"
              style={{ fontSize: 12, color: palette.primary }}
            >
              {errorMessage}
            </CuteText>
          ) : null}
          {infoMessage && !errorMessage ? (
            <CuteText
              tone="muted"
              style={{ fontSize: 12, color: palette.text }}
            >
              {infoMessage}
            </CuteText>
          ) : null}
          <CuteButton
            label={joinLabel}
            onPress={handleJoinCouple}
            disabled={!joinCode.trim() || isJoining}
          />
        </CuteCard>
      </View>

      <CuteText
        style={{
          fontSize: 12,
          textAlign: "center",
          color: palette.primary,
          fontWeight: "600",
        }}
      >
        Signed in as {auth.user.displayName ?? "you"}
      </CuteText>
    </Screen>
  );
}
